- hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Backup Configuration VYOS router 
      vyos_config:
        backup: yes
	      backup_options:
          dir_path: /data/backup/vyos

