- hosts: '{{ hostname }}'
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Configure Hostname
      vyos_config:
        lines: 
          - set system host-name {{ inventory_hostname }}

